#towns
nhtowns = ['Acworth-nh', 'Albany-nh', 'Alexandria-nh', 'Allenstown-nh', 'Alstead-nh', 'Alton-nh', 'Amherst-nh',
    'Andover-nh', 'Antrim-nh', 'Ashland-nh', 'Atkinson-nh', 'Auburn-nh', 'Barnstead-nh', 'Barrington-nh',
    'Bartlett-nh', 'Bath-nh', 'Bedford-nh', 'Belmont-nh', 'Bennington-nh', 'Benton-nh', 'Berlin-nh',
    'Bethlehem-nh', 'Boscawen-nh', 'Bow-nh', 'Bradford-nh', 'Brentwood-nh', 'Bridgewater-nh', 'Bristol-nh',
    'Brookfield-nh', 'Brookline-nh', 'Campton-nh', 'Canaan-nh', 'Candia-nh', 'Canterbury-nh', 'Carroll-nh',
    'Center Harbor-nh', 'Charlestown-nh', 'Chatham-nh', 'Chester-nh', 'Chesterfield-nh', 'Chichester-nh',
    'Claremont-nh', 'Clarksville-nh', 'Colebrook-nh', 'Columbia-nh', 'Concord-nh', 'Conway-nh', 'Cornish-nh',
    'Croydon-nh', 'Dalton-nh', 'Danbury-nh', 'Danville-nh', 'Deerfield-nh', 'Deering-nh', 'Derry-nh',
    'Dorchester-nh', 'Dover-nh', 'Dublin-nh', 'Dummer-nh', 'Dunbarton-nh', 'Durham-nh', 'East Kingston-nh',
    'Easton-nh', 'Eaton-nh', 'Effingham-nh', 'Ellsworth-nh', 'Enfield-nh', 'Epping-nh', 'Epsom-nh',
    'Errol-nh', 'Exeter-nh', 'Farmington-nh', 'Fitzwilliam-nh', 'Francestown-nh', 'Franconia-nh',
    'Franklin-nh', 'Freedom-nh', 'Fremont-nh', 'Gilford-nh', 'Gilmanton-nh', 'Gilsum-nh', 'Goffstown-nh',
    'Gorham-nh', 'Goshen-nh', 'Grafton-nh', 'Grantham-nh', 'Greenfield-nh', 'Greenland-nh', 'Greenville-nh',
    'Groton-nh', 'Hampstead-nh', 'Hampton-nh', 'Hampton Falls-nh', 'Hancock-nh', 'Hanover-nh', 'Harrisville-nh',
    'Harts Location-nh', 'Haverhill-nh', 'Hebron-nh', 'Henniker-nh', 'Hill-nh', 'Hillsborough-nh',
    'Hinsdale-nh', 'Holderness-nh', 'Hollis-nh', 'Hooksett-nh', 'Hopkinton-nh', 'Hudson-nh','Jackson-nh', 'Jaffrey-nh', 'Jefferson-nh', 'Keene-nh', 'Kensington-nh', 'Kingston-nh', 'Laconia-nh',
    'Lancaster-nh', 'Landaff-nh', 'Langdon-nh', 'Lebanon-nh', 'Lee-nh', 'Lempster-nh', 'Lincoln-nh',
    'Lisbon-nh', 'Litchfield-nh', 'Littleton-nh', 'Londonderry-nh', 'Loudon-nh', 'Lyman-nh', 'Lyme-nh',
    'Lyndeborough-nh', 'Madbury-nh', 'Madison-nh', 'Manchester-nh', 'Marlborough-nh', 'Marlow-nh',
    'Mason-nh', 'Meredith-nh', 'Merrimack-nh', 'Middleton-nh', 'Milan-nh', 'Milford-nh', 'Milton-nh',
    'Monroe-nh', 'Mont Vernon-nh', 'Moultonborough-nh', 'Nashua-nh', 'Nelson-nh', 'New Boston-nh',
    'New Castle-nh', 'New Durham-nh', 'New Hampton-nh', 'New Ipswich-nh', 'New London-nh', 'Newbury-nh',
    'Newfields-nh', 'Newington-nh', 'Newmarket-nh', 'Newport-nh', 'Newton-nh', 'North Hampton-nh',
    'Northfield-nh', 'Northumberland-nh', 'Northwood-nh', 'Nottingham-nh', 'Orange-nh', 'Orford-nh',
    'Ossipee-nh', 'Pelham-nh', 'Pembroke-nh', 'Peterborough-nh', 'Piermont-nh', 'Pinkhams Grant-nh',
    'Pittsburg-nh', 'Pittsfield-nh', 'Plainfield-nh', 'Plaistow-nh', 'Plymouth-nh', 'Portsmouth-nh',
    'Randolph-nh', 'Raymond-nh', 'Richmond-nh', 'Rindge-nh', 'Rochester-nh', 'Rollinsford-nh',
    'Roxbury-nh', 'Rumney-nh', 'Rye-nh', 'Salem-nh', 'Salisbury-nh', 'Sanbornton-nh', 'Sandown-nh',
    'Sandwich-nh', 'Seabrook-nh', 'Sharon-nh', 'Shelburne-nh', 'Somersworth-nh', 'South Hampton-nh',
    'Springfield-nh', 'Stark-nh', 'Stewartstown-nh', 'Stoddard-nh', 'Strafford-nh', 'Stratham-nh',
    'Sugar Hill-nh', 'Sullivan-nh', 'Sunapee-nh', 'Surry-nh', 'Sutton-nh', 'Swanzey-nh', 'Tamworth-nh',
    'Temple-nh', 'Thornton-nh', 'Tilton-nh', 'Troy-nh', 'Tuftonboro-nh', 'Unity-nh', 'Wakefield-nh',
    'Walpole-nh', 'Warner-nh', 'Warren-nh', 'Washington-nh', 'Waterville Valley-nh','Weare-nh', 'Webster-nh', 'Wentworth-nh', 'Westmoreland-nh', 'Whitefield-nh', 'Wilmot-nh',
    'Wilton-nh', 'Winchester-nh', 'Windham-nh', 'Windsor-nh', 'Wolfeboro-nh', 'Woodstock-nh']
vttowns = ['Albany-vt', 'Alburgh-vt', 'Andover-vt', 'Arlington-vt', 'Athens-vt', 'Averill-vt', 'Bakersfield-vt',
    'Baltimore-vt', 'Barnard-vt', 'Barnet-vt', 'Barre-vt', 'Barton-vt', 'Bellows Falls-vt', 'Belmont-vt',
    'Belvidere-vt', 'Bennington-vt', 'Benson-vt', 'Berkshire-vt', 'Berlin-vt', 'Bethel-vt', 'Bloomfield-vt',
    'Bolton-vt', 'Bradford-vt', 'Braintree-vt', 'Brandon-vt', 'Brattleboro-vt', 'Bridgewater-vt',
    'Bridport-vt', 'Brighton-vt', 'Bristol-vt', 'Brookfield-vt', 'Brookline-vt', 'Brownington-vt',
    'Brunswick-vt', 'Burke-vt', 'Burlington-vt', 'Cabot-vt', 'Calais-vt', 'Cambridge-vt', 'Canaan-vt',
    'Castleton-vt', 'Cavendish-vt', 'Charleston-vt', 'Charlotte-vt', 'Chelsea-vt', 'Chester-vt',
    'Chittenden-vt', 'Clarendon-vt', 'Colchester-vt', 'Concord-vt', 'Corinth-vt', 'Cornwall-vt',
    'Coventry-vt', 'Craftsbury-vt', 'Danby-vt', 'Danville-vt', 'Derby-vt', 'Dorset-vt', 'Dover-vt',
    'Dummerston-vt', 'Duxbury-vt', 'East Haven-vt', 'East Montpelier-vt', 'Eden-vt', 'Elmore-vt',
    'Enosburg-vt', 'Essex-vt', 'Fair Haven-vt', 'Fairfax-vt', 'Fairfield-vt', 'Fairlee-vt',
    'Fayston-vt', 'Ferdinand-vt', 'Ferrisburgh-vt', 'Fletcher-vt', 'Franklin-vt', 'Georgia-vt',
    'Glastenbury-vt', 'Glover-vt', 'Goshen-vt', 'Grafton-vt', 'Granby-vt', 'Grand Isle-vt', 'Granville-vt',
    'Greensboro-vt', 'Groton-vt', 'Guildhall-vt', 'Guilford-vt', 'Halifax-vt', 'Hancock-vt',
    'Hardwick-vt', 'Hartford-vt', 'Hartland-vt', 'Highgate-vt', 'Hinesburg-vt', 'Holland-vt',
    'Hubbardton-vt', 'Huntington-vt', 'Hyde Park-vt', 'Ira-vt', 'Irasburg-vt', 'Isle La Motte-vt',
    'Jacksonville-vt', 'Jamaica-vt', 'Jay-vt', 'Jericho-vt', 'Johnson-vt', 'Killington-vt',
    'Kirby-vt', 'Landgrove-vt', 'Leicester-vt', 'Lemington-vt', 'Lewis-vt', 'Lincoln-vt', 'Londonderry-vt', 'Lowell-vt', 'Ludlow-vt', 'Lunenburg-vt', 'Lyndon-vt', 'Maidstone-vt', 'Manchester-vt',
    'Marlboro-vt', 'Marshfield-vt', 'Mendon-vt', 'Middlebury-vt', 'Middlesex-vt', 'Middletown Springs-vt',
    'Milton-vt', 'Monkton-vt', 'Montgomery-vt', 'Montpelier-vt', 'Moretown-vt', 'Morgan-vt', 'Morristown-vt',
    'Mount Holly-vt', 'Mount Tabor-vt', 'Newark-vt', 'Newbury-vt', 'Newfane-vt', 'Newport-vt', 'North Bennington-vt',
    'North Hero-vt', 'Northfield-vt', 'Norton-vt', 'Norwich-vt', 'Orange-vt', 'Orwell-vt', 'Panton-vt',
    'Pawlet-vt', 'Peacham-vt', 'Perkinsville-vt', 'Pittsfield-vt', 'Pittsford-vt', 'Plainfield-vt',
    'Plymouth-vt', 'Pomfret-vt', 'Poultney-vt', 'Pownal-vt', 'Proctor-vt', 'Putney-vt', 'Quechee-vt',
    'Randolph-vt', 'Reading-vt', 'Readsboro-vt', 'Richford-vt', 'Richmond-vt', 'Ripton-vt', 'Rochester-vt',
    'Rockingham-vt', 'Roxbury-vt', 'Royalton-vt', 'Rupert-vt', 'Rutland-vt', 'Ryegate-vt', 'Salisbury-vt',
    'Saxtons River-vt', 'Searsburg-vt', 'Shaftsbury-vt', 'Sharon-vt', 'Sheffield-vt', 'Shelburne-vt',
    'Sheldon-vt', 'Sherburne-vt', 'Shoreham-vt', 'Shrewsbury-vt', 'Somerset-vt', 'South Burlington-vt',
    'South Hero-vt', 'Springfield-vt', 'St. Albans-vt', 'St. George-vt', 'St. Johnsbury-vt', 'Stamford-vt',
    'Stannard-vt', 'Starksboro-vt', 'Stockbridge-vt', 'Stowe-vt', 'Strafford-vt', 'Stratton-vt', 'Sudbury-vt',
    'Sutton-vt', 'Swanton-vt', 'Thetford-vt', 'Tinmouth-vt', 'Topsham-vt', 'Townshend-vt', 'Troy-vt',
    'Tunbridge-vt', 'Underhill-vt', 'Vergennes-vt', 'Vernon-vt', 'Vershire-vt', 'Victory-vt', 'Waite-vt',
    'Waitsfield-vt', 'Walden-vt', 'Wallingford-vt', 'Waltham-vt', 'Wardsboro-vt', 'Warren-vt', 'Washington-vt',
    'Waterbury-vt', 'Waterford-vt', 'Waterville-vt', 'Weathersfield-vt', 'Wells-vt', 'West Fairlee-vt',
    'West Haven-vt', 'West Rutland-vt', 'West Topsham-vt', 'Westminster-vt', 'Westmore-vt', 'Weybridge-vt',
    'White River Junction-vt', 'Whiting-vt', 'Whitingham-vt', 'Wilder-vt', 'Williamstown-vt', 'Williston-vt',
    'Wilmington-vt', 'Winhall-vt', 'Winooski-vt', 'Wolcott-vt', 'Woodbury-vt', 'Woodstock-vt', 'Worcester-vt']

nhtowns_2 = ['Hudson-nh','Jackson-nh', 'Jaffrey-nh', 'Jefferson-nh', 'Keene-nh', 'Kensington-nh', 'Kingston-nh', 'Laconia-nh',
    'Lancaster-nh', 'Landaff-nh', 'Langdon-nh', 'Lebanon-nh', 'Lee-nh', 'Lempster-nh', 'Lincoln-nh',
    'Lisbon-nh', 'Litchfield-nh', 'Littleton-nh', 'Londonderry-nh', 'Loudon-nh', 'Lyman-nh', 'Lyme-nh',
    'Lyndeborough-nh', 'Madbury-nh', 'Madison-nh', 'Manchester-nh', 'Marlborough-nh', 'Marlow-nh',
    'Mason-nh', 'Meredith-nh', 'Merrimack-nh', 'Middleton-nh', 'Milan-nh', 'Milford-nh', 'Milton-nh',
    'Monroe-nh', 'Mont Vernon-nh', 'Moultonborough-nh', 'Nashua-nh', 'Nelson-nh', 'New Boston-nh',
    'New Castle-nh', 'New Durham-nh', 'New Hampton-nh', 'New Ipswich-nh', 'New London-nh', 'Newbury-nh',
    'Newfields-nh', 'Newington-nh', 'Newmarket-nh', 'Newport-nh', 'Newton-nh', 'North Hampton-nh',
    'Northfield-nh', 'Northumberland-nh', 'Northwood-nh', 'Nottingham-nh', 'Orange-nh', 'Orford-nh',
    'Ossipee-nh', 'Pelham-nh', 'Pembroke-nh', 'Peterborough-nh', 'Piermont-nh', 'Pinkhams Grant-nh',
    'Pittsburg-nh', 'Pittsfield-nh', 'Plainfield-nh', 'Plaistow-nh', 'Plymouth-nh', 'Portsmouth-nh',
    'Randolph-nh', 'Raymond-nh', 'Richmond-nh', 'Rindge-nh', 'Rochester-nh', 'Rollinsford-nh',
    'Roxbury-nh', 'Rumney-nh', 'Rye-nh', 'Salem-nh', 'Salisbury-nh', 'Sanbornton-nh', 'Sandown-nh',
    'Sandwich-nh', 'Seabrook-nh', 'Sharon-nh', 'Shelburne-nh', 'Somersworth-nh', 'South Hampton-nh',
    'Springfield-nh', 'Stark-nh', 'Stewartstown-nh', 'Stoddard-nh', 'Strafford-nh', 'Stratham-nh',
    'Sugar Hill-nh', 'Sullivan-nh', 'Sunapee-nh', 'Surry-nh', 'Sutton-nh', 'Swanzey-nh', 'Tamworth-nh',
    'Temple-nh', 'Thornton-nh', 'Tilton-nh', 'Troy-nh', 'Tuftonboro-nh', 'Unity-nh', 'Wakefield-nh',
    'Walpole-nh', 'Warner-nh', 'Warren-nh', 'Washington-nh', 'Waterville Valley-nh','Weare-nh', 'Webster-nh', 'Wentworth-nh', 'Westmoreland-nh', 'Whitefield-nh', 'Wilmot-nh',
    'Wilton-nh', 'Winchester-nh', 'Windham-nh', 'Windsor-nh', 'Wolfeboro-nh', 'Woodstock-nh']

mainetowns = ['Abbot-me', 'Acton-me', 'Addison-me', 'Albion-me', 'Alexander-me', 'Alfred-me', 'Alna-me', 'Alton-me', 'Andover-me', 'Anson-me', 'Appleton-me', 'Arundel-me', 'Ashland-me', 'Athens-me', 'Auburn-me', 'Augusta-me', 'Baileyville-me', 'Baldwin-me', 'Bangor-me', 'Bar-Harbor-me', 'Bath-me', 'Belfast-me', 'Belgrade-me', 'Belmont-me', 'Benton-me', 'Berwick-me', 'Bethel-me', 'Biddeford-me', 'Bingham-me', 'Blaine-me', 'Blue-Hill-me', 'Boothbay-me', 'Boothbay-Harbor-me', 'Bowdoin-me', 'Bowdoinham-me', 'Bradford-me', 'Bradley-me', 'Bremen-me', 'Brewer-me', 'Bridgewater-me', 'Bridgton-me', 'Bristol-me', 'Brooklin-me', 'Brooks-me', 'Brooksville-me', 'Brownfield-me', 'Brownville-me', 'Brunswick-me', 'Buckfield-me', 'Bucksport-me', 'Burnham-me', 'Buxton-me', 'Calais-me', 'Camden-me', 'Canaan-me', 'Canton-me', 'Cape-Elizabeth-me', 'Caribou-me', 'Carmel-me', 'Carrabassett-Valley-me', 'Carthage-me', 'Casco-me', 'Castine-me', 'Charleston-me', 'Chelsea-me', 'Cherryfield-me', 'Chester-me', 'Chesterville-me', 'China-me', 'Clifton-me', 'Clinton-me', 'Corinna-me', 'Corinth-me', 'Cornish-me', 'Cornville-me', 'Cumberland-me', 'Cushing-me', 'Cutler-me', 'Damariscotta-me', 'Danforth-me', 'Dayton-me', 'Dedham-me', 'Deer-Isle-me', 'Denmark-me', 'Detroit-me', 'Dexter-me', 'Dixfield-me', 'Dixmont-me', 'Dover-Foxcroft-me', 'Dresden-me', 'Durham-me', 'Eagle-Lake-me', 'East-Machias-me', 'East-Millinocket-me', 'Easton-me', 'Eastport-me', 'Eddington-me', 'Edgecomb-me', 'Eliot-me', 'Ellsworth-me', 'Embden-me', 'Enfield-me', 'Etna-me', 'Eustis-me', 'Exeter-me', 'Fairfield-me', 'Falmouth-me', 'Farmingdale-me', 'Farmington-me', 'Fayette-me', 'Fort-Fairfield-me', 'Fort-Kent-me', 'Frankfort-me', 'Franklin-me', 'Freedom-me', 'Freeport-me', 'Frenchville-me', 'Friendship-me', 'Fryeburg-me', 'Gardiner-me', 'Garland-me', 'Georgetown-me', 'Glenburn-me', 'Gorham-me', 'Gouldsboro-me', 'Gray-me', 'Greenbush-me', 'Greene-me', 'Greenville-me', 'Greenwood-me', 'Guilford-me', 'Hallowell-me', 'Hampden-me', 'Hancock-me', 'Harmony-me', 'Harpswell-me', 'Harrington-me', 'Harrison-me', 'Hartford-me', 'Hartland-me', 'Hebron-me', 'Hermon-me', 'Hiram-me', 'Hodgdon-me', 'Holden-me', 'Hollis-me', 'Hope-me', 'Houlton-me', 'Howland-me', 'Hudson-me', 'Industry-me', 'Island-Falls-me', 'Islesboro-me', 'Jackman-me', 'Jackson-me', 'Jay-me', 'Jefferson-me', 'Jonesboro-me', 'Jonesport-me', 'Kenduskeag-me', 'Kennebunk-me', 'Kennebunkport-me', 'Kingfield-me', 'Kittery-me', 'Knox-me', 'Lagrange-me', 'Lamoine-me', 'Lebanon-me', 'Lee-me', 'Leeds-me', 'Levant-me', 'Lewiston-me', 'Liberty-me', 'Limerick-me', 'Limestone-me', 'Limington-me', 'Lincoln-me', 'Lincolnville-me', 'Linneus-me', 'Lisbon-me', 'Litchfield-me', 'Littleton-me', 'Livermore-me', 'Livermore-Falls-me', 'Lovell-me', 'Lubec-me', 'Lyman-me', 'Machias-me', 'Machiasport-me', 'Madawaska-me', 'Madison-me', 'Manchester-me', 'Mapleton-me', 'Mars-Hill-me', 'Marshfield-me', 'Mattawamkeag-me', 'Mechanic-Falls-me', 'Medway-me', 'Mercer-me', 'Mexico-me', 'Milbridge-me', 'Milford-me', 'Millinocket-me', 'Milo-me', 'Minot-me', 'Monmouth-me', 'Monroe-me', 'Monson-me', 'Monticello-me', 'Montville-me', 'Morrill-me', 'Mount-Desert-me', 'Mount-Vernon-me', 'Naples-me', 'New-Gloucester-me', 'New-Limerick-me', 'New-Portland-me', 'New-Sharon-me', 'New-Sweden-me', 'New-Vineyard-me', 'Newburgh-me', 'Newcastle-me', 'Newfield-me', 'Newport-me', 'Nobleboro-me', 'Norridgewock-me', 'North-Berwick-me', 'North-Yarmouth-me', 'Northport-me', 'Norway-me', 'Oakfield-me', 'Oakland-me', 'Ogunquit-me', 'Old-Orchard-Beach-me', 'Old-Town-me', 'Orland-me', 'Orono-me', 'Orrington-me', 'Otis-me', 'Otisfield-me', 'Owls-Head-me', 'Oxford-me', 'Palermo-me', 'Palmyra-me', 'Paris-me', 'Parkman-me', 'Parsonsfield-me', 'Patten-me', 'Pembroke-me', 'Penobscot-me', 'Perry-me', 'Peru-me', 'Phillips-me', 'Phippsburg-me', 'Pittsfield-me', 'Pittston-me', 'Plymouth-me', 'Poland-me', 'Porter-me', 'Portland-me', 'Pownal-me', 'Presque-Isle-me', 'Princeton-me', 'Prospect-me', 'Randolph-me', 'Rangeley-me', 'Raymond-me', 'Readfield-me', 'Richmond-me', 'Robbinston-me', 'Rockland-me', 'Rockport-me', 'Rome-me', 'Rumford-me', 'Sabattus-me', 'Saco-me', 'Sanford-me', 'Sangerville-me', 'Scarborough-me', 'Searsmont-me', 'Searsport-me', 'Sebago-me', 'Sebec-me', 'Sedgwick-me', 'Shapleigh-me', 'Sherman-me', 'Sidney-me', 'Skowhegan-me', 'Smithfield-me', 'Solon-me', 'Somerville-me', 'South-Berwick-me', 'South-Bristol-me', 'South-Portland-me', 'South-Thomaston-me', 'Southport-me', 'Southwest-Harbor-me', 'St.-Agatha-me', 'St.-Albans-me', 'St.-George-me', 'Standish-me', 'Starks-me', 'Stetson-me', 'Steuben-me', 'Stockton-Springs-me', 'Stonington-me', 'Strong-me', 'Sullivan-me', 'Sumner-me', 'Surry-me', 'Swanville-me', 'Temple-me', 'Thomaston-me', 'Thorndike-me', 'Topsham-me', 'Tremont-me', 'Trenton-me', 'Troy-me', 'Turner-me', 'Union-me', 'Unity-me', 'Van-Buren-me', 'Vassalboro-me', 'Veazie-me', 'Verona-Island-me', 'Vienna-me', 'Vinalhaven-me', 'Waldo-me', 'Waldoboro-me', 'Wales-me', 'Wallagrass-me', 'Warren-me', 'Washburn-me', 'Washington-me', 'Waterboro-me', 'Waterford-me', 'Waterville-me', 'Wayne-me', 'Wells-me', 'West-Bath-me', 'West-Gardiner-me', 'West-Paris-me', 'Westbrook-me', 'Westport-Island-me', 'Whitefield-me', 'Wilton-me', 'Windham-me', 'Windsor-me', 'Winslow-me', 'Winterport-me', 'Winthrop-me', 'Wiscasset-me', 'Woodland-me', 'Woodstock-me', 'Woolwich-me', 'Yarmouth-me', 'York-me']